### ISSUE TITLE
📋 Crate compatibility tracker

### ISSUE THREAD

**Issue by fasterthanlime** [bearcove/rubicon#3]
Here are temporary PRs:

  * [ ] https://github.com/bearcove/tokio/pull/2
  * [ ] https://github.com/bearcove/tracing/pull/1
  * [ ] https://github.com/bearcove/parking_lot/pull/1
  * eyre:
    * [ ] https://github.com/bearcove/eyre/pull/1
    * [ ] https://github.com/bearcove/eyre/pull/2

---

For anyone playing around with rubicon, the easiest way to get your crate graph to use rubicon-compatible crates is to use crates.io patching, _not_ in `Cargo.toml`, since you'd have to duplicate those in your app, mods, and exports crate, but in `.cargo/config.toml`, somewhere in your repository, something like:

### Sample `.cargo/config.toml`

```toml
[target.'cfg(any())']
rustflags = [
    # generic flags
    "-Wunused-crate-dependencies",
    "-Cprefer-dynamic",
]

[target.'cfg(any(target_os = "macos"))']
rustflags = [
    # macOS-specific flags
    "-Wunused-crate-dependencies",
    "-Cprefer-dynamic",
    "-Clink-arg=-undefined",
    "-Clink-arg=dynamic_lookup",
]

[patch.crates-io]
tracing-subscriber = { git = "https://github.com/bearcove/tracing", branch = "v0.1.x-rubicon-3.x" }
tracing-core = { git = "https://github.com/bearcove/tracing", branch = "v0.1.x-rubicon-3.x" }
tracing-log = { git = "https://github.com/bearcove/tracing", branch = "v0.1.x-rubicon-3.x" }
tracing = { git = "https://github.com/bearcove/tracing", branch = "v0.1.x-rubicon-3.x" }

tokio = { git = "https://github.com/bearcove/tokio", branch = "rubicon-3.x-bis" }

parking_lot = { git = "https://github.com/bearcove/parking_lot", branch = "rubicon-3.x" }
parking_lot_core = { git = "https://github.com/bearcove/parking_lot", branch = "rubicon-3.x" }
lock_api = { git = "https://github.com/bearcove/parking_lot", branch = "rubicon-3.x" }

eyre = { git = "https://github.com/bearcove/eyre", branch = "release-0.6-rubicon-3.x" }
```
